In [1]:
from google.colab import drive 
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [2]:
%cd "drive/My Drive/keikiwatcher_forcolab"

/content/drive/My Drive/keikiwatcher_forcolab


In [0]:
import pandas as pd
current = pd.read_csv("current_v3.csv",encoding="utf-8-sig")
current = current.drop("detail", axis=1).drop("dos", axis=1).drop("region",axis=1).drop("uno",axis=1).drop("when",axis=1).drop("section",axis=1).rename(columns={'sig':'s'}).rename(columns={'comment':'text'})
future = pd.read_csv("future_v3.csv",encoding="utf-8-sig")
future = future.drop("detail", axis=1).drop("dos", axis=1).drop("region",axis=1).drop("uno",axis=1).drop("when",axis=1).drop("section",axis=1).rename(columns={'sig':'s'}).rename(columns={'comment':'text'})

In [4]:
df = current.append(future).reset_index().drop("index",axis=1)
#df


# In[5]:


s_l = df["s"].to_list()

s_ll = []
for i in s_l:
    a = i.replace("◎","4")
    b = a.replace("○","3")
    c = b.replace("□","2")
    d = c.replace("▲","1")
    e = d.replace("×","0")
    s_ll.append(e)
    
df["s"] = s_ll
df



text  s
0                                                       ＊  4
1       ・６月に入り、全道的なスポーツ大会や会議などが相次ぎ、当地域を訪れる来街者が増加した。特に飲...  3
2       ・今年の夏はスーパー、ドラッグストアの新店オープンが次々と予定されていることから、建設関係を...  3
3       ・以前と比べて、来客数が前年比で上向いている。５月は天候要因による影響とみられたが、６月も回...  3
4           ・５月後半に暑い日が続いたことから、６月前半からエアコンなどの夏物家電が好調に売れている。  3
...                                                   ... ..
498199  ・景気の足を引っ張るようなニュースが続いているため、企業は引き締め感がとても強い。具体的に派...  2
498200                                    ・全体的に様子見の気配がある。  2
498201  ・平成19年度の管内の常用有効求人倍率が前年度より0.09ポイント下降、新規求人倍率が0.0...  1
498202  ・大手企業の来期利益がマイナスとの報道を受け、一部の企業で既に採用枠を抑えているという情報も...  1
498203                                                  －  0

[498204 rows x 2 columns]

In [5]:
wa = []
for i in df["text"]:
    try:
        a = i.split("。")
        b = a[0].replace("・","")
        wa.append(b)
    except:
        wa.append("Nan")
        
df["text"] = wa
#df

# In[7]:
aa = df.groupby("s")
#aa.size()

# In[8]:
X = df["text"]
X

0                                                         ＊
1                 ６月に入り、全道的なスポーツ大会や会議などが相次ぎ、当地域を訪れる来街者が増加した
2         今年の夏はスーパー、ドラッグストアの新店オープンが次々と予定されていることから、建設関係を中...
3                                     以前と比べて、来客数が前年比で上向いている
4               ５月後半に暑い日が続いたことから、６月前半からエアコンなどの夏物家電が好調に売れている
                                ...                        
498199              景気の足を引っ張るようなニュースが続いているため、企業は引き締め感がとても強い
498200                                        全体的に様子見の気配がある
498201    平成19年度の管内の常用有効求人倍率が前年度より0.09ポイント下降、新規求人倍率が0.07...
498202    大手企業の来期利益がマイナスとの報道を受け、一部の企業で既に採用枠を抑えているという情報もあ...
498203                                                    －
Name: text, Length: 498204, dtype: object

In [6]:
#https://qiita.com/Fulltea/items/90f6ebe6dcceaf64eaef
!apt install aptitude swig
!aptitude install mecab libmecab-dev mecab-ipadic-utf8 git make curl xz-utils file -y
!pip install mecab-python3

Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  aptitude-common libcgi-fast-perl libcgi-pm-perl libclass-accessor-perl
  libcwidget3v5 libencode-locale-perl libfcgi-perl libhtml-parser-perl
  libhtml-tagset-perl libhttp-date-perl libhttp-message-perl libio-html-perl
  libio-string-perl liblwp-mediatypes-perl libparse-debianchangelog-perl
  libsigc++-2.0-0v5 libsub-name-perl libtimedate-perl liburi-perl libxapian30
  swig3.0
Suggested packages:
  aptitude-doc-en | aptitude-doc apt-xapian-index debtags tasksel
  libcwidget-dev libdata-dump-perl libhtml-template-perl libxml-simple-perl
  libwww-perl xapian-tools swig-doc swig-examples swig3.0-examples swig3.0-doc
The following NEW packages will be installed:
  aptitude aptitude-common libcgi-fast-perl libcgi-pm-perl
  libclass-accessor-perl libcwidget3v5 libencode-locale-perl libfcgi-perl
  libhtml-parser-perl libhtml-tagset-perl libhttp

In [0]:
!git clone --depth 1 https://github.com/neologd/mecab-ipadic-neologd.git
#!echo yes | mecab-ipadic-neologd/bin/install-mecab-ipadic-neologd -n -a

fatal: destination path 'mecab-ipadic-neologd' already exists and is not an empty directory.


In [0]:
#import MeCab
#import subprocess

#cmd='echo `mecab-config --dicdir`"/mecab-ipadic-neologd"'
#path = (subprocess.Popen(cmd, stdout=subprocess.PIPE, shell=True).communicate()[0]).decode('utf-8')
#m=MeCab.Tagger("-d {0}".format(path))
#tagger=MeCab.Tagger()

In [0]:
# ストップワードの除去：使用頻度の高い言葉を処理対象外にする
import MeCab

def token_generator(text):
    # mecab-ipadic-NEologd辞書指定してオブジェクト生成
    tagger = MeCab.Tagger()
    tagger.parse("")
    # 形態素解析の結果をリストで取得、単語ごとにリストの要素に入ってる
    node = tagger.parseToNode(text)
    result = []
    
    num = 0
    oldhinshi = "" # 一つ前のトークンの品詞

    #助詞や助動詞は拾わない
    while node is not None:
        # 品詞情報取得
        # Node.featureのフォーマット：品詞,品詞細分類1,品詞細分類2,品詞細分類3,活用形,活用型,原形,読み,発音
        hinshi = node.feature.split(",")[0]
        if hinshi in["動詞","形容詞"]:
            # 形態素情報から原形情報取得
            result.append(node.feature.split(",")[6])
            oldhinshi = hinshi # oldhinshiの更新

        elif hinshi in ["副詞"]:
            # 表層形の取得、単語の文字が入ってる
            result.append(node.surface)
            oldhinshi = hinshi # oldhinshiの更新
        
        elif hinshi in ["名詞"]:
            # 表層形の取得、単語の文字が入ってる
            if oldhinshi != '名詞': 
                result.append(node.surface)
                num += 1 # インデックス指定のためにnumで番号を振っておく
                oldhinshi = hinshi # oldhinshiの更新
            else: # oldhinshiが名詞の場合
                result[num-1] = result[num-1]+node.surface # 一つ前のトークンに接続
                oldhinshi = hinshi # oldhinshiの更新
        else:
            oldhinshi = hinshi # oldhinshiの更新
            
        node = node.next

    return result
 

In [0]:
fulltoken = []
errors = []
for i in range(len(X)):
    try:
        a = token_generator(X[i])
        fulltoken.append(a)
        print(i)
    except:
        print("error "+str(i))
        errors.append(i)# トークン作成に時間がかかったので、毎回処理を行わなくてもいいようにpickleファイルに押し込みました。

ストリーミング出力は最後の 5000 行に切り捨てられました。
493205
493206
493207
493208
493209
493210
493211
493212
493213
493214
493215
493216
493217
493218
493219
493220
493221
493222
493223
493224
493225
493226
493227
493228
493229
493230
493231
493232
493233
493234
493235
493236
493237
493238
493239
493240
493241
493242
493243
493244
493245
493246
493247
493248
493249
493250
493251
493252
493253
493254
493255
493256
493257
493258
493259
493260
493261
493262
493263
493264
493265
493266
493267
493268
493269
493270
493271
493272
493273
493274
493275
493276
493277
493278
493279
493280
493281
493282
493283
493284
493285
493286
493287
493288
493289
493290
493291
493292
493293
493294
493295
493296
493297
493298
493299
493300
493301
493302
493303
493304
493305
493306
493307
493308
493309
493310
493311
493312
493313
493314
493315
493316
493317
493318
493319
493320
493321
493322
493323
493324
493325
493326
493327
493328
493329
493330
493331
493332
493333
493334
493335
493336
493337
493338
493339
493340
493341
493342
49

In [0]:
fulltoken[:10]

[[],
 ['６月', '入る的', '道大会', 'スポーツ', '会議', '相次ぐ者', '地域', '訪れる', '街', '増加', 'する'],
 ['今年',
  '夏',
  'スーパー',
  'ドラッグストア',
  '新店オープン',
  '次々',
  '予定',
  'する関係',
  'れる',
  'いる',
  'こと',
  '建設',
  '中心',
  '忙しい',
  '状況',
  '続く',
  'いる'],
 ['以前', '比べる数', '来客比', '前年', '上向く', 'いる'],
 ['５月後半', '暑い', '日', '続く前半', 'こと', '６月家電', 'エアコン', '夏物', '好調', '売れる', 'いる'],
 ['全体的', '前年', '上回る', 'やや', '良い'],
 ['国内', '報奨旅行', '効率', '良い', '受注', 'できる'],
 ['10連休',
  'なる',
  'ゴールデンウィーク',
  '集客',
  '良い',
  'こと',
  '反動',
  '６月',
  '花',
  '観光',
  '集客',
  '今一つ',
  '伸びる'],
 ['通信端末',
  '料金変更',
  '行う',
  'こと数',
  '来客',
  '前年.8倍',
  '1',
  '増加量',
  'する',
  'おる',
  '販売',
  '増加',
  'する',
  'いる'],
 ['技術売上', '関連商材', '販売量', '数か月連続', '前年', '上回る', 'いる']]

In [0]:
import pickle
with open('fulltoken.pickle', 'wb') as f:
    pickle.dump(fulltoken , f)
with open('errors.pickle', 'wb') as f:
    pickle.dump(errors , f)
# In[11]:



In [0]:
import pickle
with open('fulltoken.pickle','rb') as f:
    fulltoken = pickle.load(f)

with open('errors.pickle','rb') as f:
    errors = pickle.load(f)


df_ = df.drop(df.index[errors])

In [0]:
import numpy as np

label = df_["s"]
label = [float(i) for i in label]
label = np.array(label)




# 特殊なトークンは事前に定義しておく
PAD_TOKEN = '<PAD>'  # バッチ処理の際に、短い系列の末尾を埋めるために使う （Padding）
UNK_TOKEN = '<Unknown>'  # 語彙に存在しない単語を表す （Unknown）
PAD = 0
UNK = 1


# In[20]:


MIN_COUNT = 2  # 語彙に含める単語の最低出現回数

# 単語をIDに変換する辞書の初期値を設定
word2id = {
    PAD_TOKEN: PAD,
    UNK_TOKEN: UNK,
    }


# In[21]:


class Vocab(object):
    def __init__(self, word2id={}):
        """
        word2id: 単語(str)をインデックス(int)に変換する辞書
        id2word: インデックス(int)を単語(str)に変換する辞書
        """
        self.word2id = dict(word2id)
        self.id2word = {v: k for k, v in self.word2id.items()}    
        
    def build_vocab(self, sentences, min_count=1):
        # 各単語の出現回数の辞書を作成する
        word_counter = {}
        for sentence in sentences:
            for word in sentence:
                word_counter[word] = word_counter.get(word, 0) + 1

        # min_count回以上出現する単語のみ語彙に加える
        for word, count in sorted(word_counter.items(), key=lambda x: -x[1]):
            if count < min_count:
                break
            _id = len(self.word2id)
            self.word2id.setdefault(word, _id)
            self.id2word[_id] = word 


vocab_Y = Vocab(word2id=word2id)
vocab_Y.build_vocab(fulltoken, min_count=MIN_COUNT)
vocab_size_Y = len(vocab_Y.id2word)



In [0]:
def sentence_to_ids(vocab, sentence):
    # 単語(str)のリストをID(int)のリストに変換する関数
    ids = [vocab.word2id.get(word, UNK) for word in sentence]
    return ids


# In[25]:


data_x_vec = [sentence_to_ids(vocab_Y, sentence) for sentence in fulltoken]
#data_x_vec[:2]


# In[26]:


# 文章の長さを揃えるため、0でパディングする
max_sentence_size = 0
for sentence_vec in data_x_vec:
    if max_sentence_size < len(sentence_vec):
        max_sentence_size = len(sentence_vec)
#print(max_sentence_size)   # ==len(sentence_ids)

for sentence_ids in data_x_vec:
    while len(sentence_ids) < max_sentence_size:
         # 末尾に0を追加
        sentence_ids.append(0)


# In[27]:


# arrayに変換
data_x_vecs = np.array(data_x_vec, dtype="int32")
#data_x_vecs



# 訓練データとテストデータにわけます
from sklearn.model_selection import train_test_split
train_x_, test_x, train_y_, test_y = train_test_split(data_x_vecs, label, test_size = 0.1)



# 訓練データとテストデータにわけます
from sklearn.model_selection import train_test_split
train_x, valid_x, train_y, valid_y = train_test_split(train_x_, train_y_, test_size = 0.2)


# In[33]:




In [12]:
!pip install tensorflow==1.14
!pip install keras

     |████████████████████████████████| 109.2MB 63kB/s 
     |████████████████████████████████| 3.2MB 49.8MB/s 
     |████████████████████████████████| 491kB 51.4MB/s 
  Found existing installation: tensorboard 2.2.0
    Uninstalling tensorboard-2.2.0:
      Successfully uninstalled tensorboard-2.2.0
  Found existing installation: tensorflow-estimator 2.2.0rc0
    Uninstalling tensorflow-estimator-2.2.0rc0:
      Successfully uninstalled tensorflow-estimator-2.2.0rc0
  Found existing installation: tensorflow 2.2.0rc2
    Uninstalling tensorflow-2.2.0rc2:
      Successfully uninstalled tensorflow-2.2.0rc2


In [13]:
import tensorflow
from keras.models import Model
from keras.layers import Input, Dense, Embedding, LSTM
from keras.layers.wrappers import Bidirectional
import keras.utils
import keras


# In[34]:


seq_len = max_sentence_size
vocab_size = len(vocab_Y.id2word)+1

from keras.models import Sequential
model = Sequential()

model.add(Embedding(input_dim=vocab_size, output_dim=128, input_length=seq_len))
model.add(Bidirectional(LSTM(units=128)))
model.add(keras.layers.Dense(units=1, activation='relu'))


# In[35]:


model.summary()

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or 

Using TensorFlow backend.


Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 58, 128)           11418624  
_________________________________________________________________
bidirectional_1 (Bidirection (None, 256)               263168    
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 257       
Total params: 11,682,049
Trainable params: 11,682,049
Non-trainable params: 0
_________________________________________________________________


In [0]:
# オプティマイザー：Adam、損失関数：（多クラス）cross entropy
model.compile(optimizer='Adam', loss='mean_squared_error')

# train
model.fit(train_x, train_y, epochs=30, batch_size=256)



Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


Epoch 1/30
201472/358706 [===============>..............] - ETA: 9:18 - loss: 0.7159

In [0]:

# モデル全体を１つのHDF5ファイルに保存します。
model.save('my_model325.h5')


In [0]:
# In[ ]:


predicts = model.predict(test_x, verbose=True)


49821/49821 [==============================] - 57s 1ms/step


In [0]:
predictslist = predicts.tolist()

def decode(datum):
    return np.argmax(datum)

test_y_list = []
for i in range(len(test_y)):
    a = decode(test_y[i])
    test_y_list.append(a)
    
testy = np.array(test_y_list)

predicts


array([[1.7830412],
       [1.3365604],
       [2.1135783],
       ...,
       [1.2616162],
       [2.0552855],
       [1.9235501]], dtype=float32)

In [0]:
count = 0
for i in range(len(testy)):
    error = abs(testy[i]-predicts[i]) # 絶対値
    count += error

count/len(predicts)

array([1.8528912], dtype=float32)

In [0]:
# In[ ]:


text1 = "景気は、失業率の問題など依然として厳しい状況にある"
text2 = "景気は緩やかな改善が続いている"
#text2 = "小中高への休業要請、直接専門家の意見聞いたものではない＝安倍首相"
texts = [text1,text2]


# In[ ]:

errors = []
target_token = []

for i in range(len(texts)):
    a = token_generator(texts[i])
    target_token.append(a)


# In[ ]:


def ids_to_sentence(vocab, ids):
    # IDのリストを単語のリストに変換する
    return [vocab.id2word[_id] for _id in ids]

def trim_eos(ids):
    # IDのリストからEOS以降の単語を除外する
    if EOS in ids:
        return ids[:ids.index(EOS)]
    else:
        return ids


# In[ ]:


test_Y_id = [sentence_to_ids(vocab_Y, sentence) for sentence in target_token]


for sentence_ids in test_Y_id:
    while len(sentence_ids) < max_sentence_size:
         # 末尾に0を追加
        sentence_ids.append(0)



a = np.array(test_Y_id)


# In[ ]:


predicts = model.predict(a, verbose=True)


# In[ ]:


predicts[0]



2/2 [==============================] - 0s 7ms/step


array([1.8879033], dtype=float32)

In [0]:

# In[ ]:


predicts[1]


array([2.864992], dtype=float32)

In [0]:
target_token

[['景気', '失業率', '依然として', '厳しい', '状況', 'ある'], ['景気', '緩やか', '改善', '続く', 'いる']]